services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${BASE}
    ports:
      - ${PORT}:5432
    networks:
      - atatek_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    ports: 
      - "8080:8080"
    networks:
      - atatek_network
    environment:
      - ADMINER_DEFAULT_SERVER=db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - atatek_network
    depends_on:
      - db
    environment:
      - HOST=db
      - PORT=5432
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - BASE=${BASE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

volumes:
  postgres_data:

networks:
  atatek_network:
    driver: bridge
